update the README.md with prototype documentation
jstephan087/portfolio-lab-2024 pull request #3
Opened 2024-08-01 11:15 UTC by mimibak

- The Basic structure for the README.md file is set

2024-08-01 15:54 UTC, jstephan087 requested changes

2024-08-01 15:54 UTC, jstephan087 commented on README.md
> +- add / edit / delete in live server preview
Hier noch ein Punkt der ergänzt werden könnte:
disable / enable section components

2024-08-01 15:54 UTC, jstephan087 commented on README.md
> +Portfolio Studio project is a concept project. Whoever symphatize with this project, feel free to fork it or contribute however possible.
Portfolio Lab

2024-08-01 15:54 UTC, jstephan087 commented on README.md
> +Saved on your local machine and deployed by yourself. Absolute self-control and also individually customizable.
Und hier noch der Zusatz:
And the best thing about it? It's free! Really free and not just pseudo free.

2024-08-02 09:09 UTC, mimibak commented on README.md
> +Portfolio Studio project is a concept project. Whoever symphatize with this project, feel free to fork it or contribute however possible.
done

2024-08-02 09:10 UTC, mimibak commented on README.md
> +- add / edit / delete in live server preview
done

2024-08-02 09:11 UTC, mimibak commented on README.md
> +Saved on your local machine and deployed by yourself. Absolute self-control and also individually customizable.
done

2024-08-02 09:30 UTC, jstephan087 approved these changes

2024-08-02 09:30 UTC, merged